version: "3"
services:
  clip-service:
    container_name: ${PROJECT_NAME}_service
    image: swissartresearx/sari-iiif-clip-search:latest
    build: .
    platform: linux/amd64
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    healthcheck:
      test: wget -q http://0.0.0.0:5000 || exit 1
      interval: 5m
      timeout: 10s
      retries: 2
      start_period: 40s
    environment:
      - CLIP_DATA_DIRECTORY=${CLIP_DATA_DIRECTORY}
    ports:
      - ${PORT}:5000
    volumes:
      - ./data:/workdir/data
      - ./precomputedFeatures:/precomputedFeatures
      - ./src:/workdir/src